name: Trigger Netlify Build
on:
  workflow_dispatch:
  schedule:
    # Run at 0000 daily
    - cron: '0 10 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/640272c78eee832f8f0c7656
